spring.application.name=student-service

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/Student

# Database username
spring.datasource.username=inventoryadmin

# Database password
spring.datasource.password=spring

# PostgresSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto table creation (use carefully)
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
